"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { format } from "date-fns";
import { getSupabaseBrowser } from "@/lib/supabase/client";
import { ConfirmDialog } from "@/components/confirm-dialog";
import { AdminButton, AdminCard, AdminInput, AdminPageHeader, StatusBadge } from "@/components/admin-ui";
import type { Post } from "@/lib/types";

type SortKey = "title" | "status" | "published_at" | "updated_at" | "like_count";
type BulkAction = "publish" | "draft" | "delete" | null;
const PAGE_SIZE = 25;

export default function AdminPostsPage() {
  const [posts, setPosts] = useState<Post[] | null>(null); const [error, setError] = useState(""); const [query, setQuery] = useState(""); const [status, setStatus] = useState<"all" | Post["status"]>("all"); const [sortKey, setSortKey] = useState<SortKey>("updated_at"); const [ascending, setAscending] = useState(false); const [page, setPage] = useState(1); const [selected, setSelected] = useState<string[]>([]); const [bulkAction, setBulkAction] = useState<BulkAction>(null); const [busy, setBusy] = useState(false);
  async function load() { setError(""); const { data, error: loadError } = await getSupabaseBrowser().from("posts").select("*").order("updated_at", { ascending: false }); if (loadError) setError(`Could not load posts: ${loadError.message}`); else setPosts((data ?? []) as Post[]); }
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => { const needle = query.trim().toLowerCase(); return [...(posts ?? [])].filter((post) => status === "all" || post.status === status).filter((post) => !needle || [post.title, post.slug, post.excerpt ?? "", ...post.tags].join(" ").toLowerCase().includes(needle)).sort((a, b) => String(a[sortKey] ?? "").localeCompare(String(b[sortKey] ?? ""), undefined, { numeric: true }) * (ascending ? 1 : -1)); }, [posts, query, sortKey, status, ascending]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const visible = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE); const allVisibleSelected = visible.length > 0 && visible.every((post) => selected.includes(post.id));
  function changeSort(key: SortKey) { if (sortKey === key) setAscending((value) => !value); else { setSortKey(key); setAscending(key === "title"); } }
  async function runBulkAction() { if (!bulkAction || selected.length === 0) return; setBusy(true); const supabase = getSupabaseBrowser(); const responses = await Promise.all(selected.map((id) => bulkAction === "delete" ? supabase.from("posts").delete().eq("id", id) : supabase.from("posts").update({ status: bulkAction === "publish" ? "published" : "draft", published_at: bulkAction === "publish" ? new Date().toISOString() : null, updated_at: new Date().toISOString() }).eq("id", id))); const failed = responses.find((response) => response.error); if (failed?.error) setError(`Bulk action failed: ${failed.error.message}`); else { setSelected([]); await load(); } setBusy(false); setBulkAction(null); }
  const tabs: { value: typeof status; label: string }[] = [{ value: "all", label: "All posts" }, { value: "draft", label: "Drafts" }, { value: "scheduled", label: "Scheduled" }, { value: "published", label: "Published" }];
  return <div className="space-y-6"><AdminPageHeader eyebrow="Content" title="Posts" description={`${filtered.length} post${filtered.length === 1 ? "" : "s"} in your workspace.`} actions={<Link href="/admin/posts/new"><AdminButton>New post</AdminButton></Link>} />
    {error ? <p role="alert" className="rounded-md border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p> : null}
    <AdminCard><div className="flex flex-col gap-3 border-b border-slate-200 p-4 sm:flex-row"><AdminInput aria-label="Search posts" value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder="Search posts…" /><select aria-label="Filter posts" value={status} onChange={(event) => { setStatus(event.target.value as typeof status); setPage(1); }} className="min-h-9 rounded-md border border-slate-300 bg-white px-3 text-sm text-slate-700 outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/20 sm:w-44">{tabs.map((tab) => <option key={tab.value} value={tab.value}>{tab.label}</option>)}</select><AdminButton variant="secondary" onClick={() => void load()}>Refresh</AdminButton></div>
      <div className="flex gap-1 overflow-x-auto border-b border-slate-200 px-4 pt-3">{tabs.map((tab) => <button key={tab.value} type="button" onClick={() => { setStatus(tab.value); setPage(1); }} className={`border-b-2 px-3 pb-3 text-sm font-medium ${status === tab.value ? "border-indigo-600 text-indigo-700" : "border-transparent text-slate-500 hover:text-slate-900"}`}>{tab.label}</button>)}</div>
      {selected.length > 0 ? <div className="flex flex-wrap items-center gap-2 border-b border-slate-200 bg-indigo-50 px-4 py-3"><span className="mr-2 text-sm font-medium text-indigo-900">{selected.length} selected</span><AdminButton variant="secondary" onClick={() => setBulkAction("publish")}>Publish</AdminButton><AdminButton variant="secondary" onClick={() => setBulkAction("draft")}>Move to draft</AdminButton><AdminButton variant="danger" onClick={() => setBulkAction("delete")}>Delete</AdminButton></div> : null}
      <div className="overflow-x-auto">{posts === null ? <p className="p-8 text-sm text-slate-500">Loading posts…</p> : filtered.length === 0 ? <p className="p-8 text-sm text-slate-500">No posts match this view.</p> : <table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs font-semibold uppercase tracking-wider text-slate-500"><tr><th className="w-12 px-5 py-3"><input type="checkbox" aria-label="Select visible posts" checked={allVisibleSelected} onChange={(event) => setSelected(event.target.checked ? [...new Set([...selected, ...visible.map((post) => post.id)])] : selected.filter((id) => !visible.some((post) => post.id === id)))} /></th><th className="px-4 py-3"><button type="button" onClick={() => changeSort("title")}>Title</button></th><th className="px-4 py-3"><button type="button" onClick={() => changeSort("status")}>Status</button></th><th className="px-4 py-3"><button type="button" onClick={() => changeSort("published_at")}>Published</button></th><th className="px-4 py-3"><button type="button" onClick={() => changeSort("updated_at")}>Updated</button></th><th className="px-4 py-3"><button type="button" onClick={() => changeSort("like_count")}>Likes</button></th></tr></thead><tbody className="divide-y divide-slate-100">{visible.map((post) => <tr key={post.id} className="hover:bg-slate-50"><td className="px-5 py-4"><input type="checkbox" aria-label={`Select ${post.title}`} checked={selected.includes(post.id)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, post.id] : current.filter((id) => id !== post.id))} /></td><td className="max-w-[360px] px-4 py-4"><Link href={`/admin/posts/${post.id}`} className="block truncate font-medium text-slate-900 hover:text-indigo-700">{post.title || "Untitled"}</Link><span className="mt-1 block truncate text-xs text-slate-500">/{post.slug}</span></td><td className="px-4 py-4"><StatusBadge status={post.status} /></td><td className="whitespace-nowrap px-4 py-4 text-slate-500">{post.published_at ? format(new Date(post.published_at), "dd MMM yyyy") : "—"}</td><td className="whitespace-nowrap px-4 py-4 text-slate-500">{format(new Date(post.updated_at), "dd MMM yyyy")}</td><td className="px-4 py-4 text-slate-500">{post.like_count ?? 0}</td></tr>)}</tbody></table>}</div>
      <div className="flex items-center justify-between border-t border-slate-200 px-5 py-4 text-xs text-slate-500"><span>Page {page} of {pageCount}</span><div className="flex gap-2"><AdminButton variant="secondary" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>Previous</AdminButton><AdminButton variant="secondary" disabled={page >= pageCount} onClick={() => setPage((value) => value + 1)}>Next</AdminButton></div></div>
    </AdminCard><ConfirmDialog open={bulkAction !== null} title={`${bulkAction === "delete" ? "Delete" : bulkAction === "publish" ? "Publish" : "Move to draft"} selected posts?`} body={bulkAction === "delete" ? "This permanently removes the selected posts and their related content." : `This will update ${selected.length} selected post${selected.length === 1 ? "" : "s"}.`} confirmLabel={bulkAction === "delete" ? "Delete posts" : "Continue"} danger={bulkAction === "delete"} busy={busy} onCancel={() => setBulkAction(null)} onConfirm={() => void runBulkAction()} /></div>;
}
